version: '2'
services:
  UbuntuBigData:
    image: 'manudf/ubuntu_pig:latest'
    stdin_open: true
    tty: true
    ports:
      - '50070:50070' # MasterNode WebUI
      - '50075:50075' # DataNode WebUI
      - '8088:8088' # ResourceManager WebUI
    volumes:
      - ./input:/home/input
      - ./output:/home/output
networks: {}
